import { precacheAndRoute } from 'workbox-precaching';

// Precaching automatically generated by VitePWA
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for push events from the backend
self.addEventListener('push', function(event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const title = data.title || 'Gita Wisdom';
      const options = {
        body: data.body || 'You have a new message.',
        icon: data.icon || '/logo-om-v2.png',
        badge: data.badge || '/logo-om-v2.png',
        data: data.data || { url: '/' },
        vibrate: [100, 50, 100],
      };

      event.waitUntil(self.registration.showNotification(title, options));
    } catch (e) {
      console.error('Error parsing push data', e);
    }
  }
});

// Handle notification click to redirect user to specific URL
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  
  if (event.notification.data && event.notification.data.url) {
    event.waitUntil(
      clients.matchAll({ type: 'window' }).then(windowClients => {
        // Check if there is already a window/tab open with the target URL
        for (let i = 0; i < windowClients.length; i++) {
          let client = windowClients[i];
          if (client.url === event.notification.data.url && 'focus' in client) {
            return client.focus();
          }
        }
        // If not, open a new window
        if (clients.openWindow) {
          return clients.openWindow(event.notification.data.url);
        }
      })
    );
  }
});
